version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Installing light streamer lib
      - mvn install:install-file -"Dfile=ig-webapi-java-client/lib/ls-client.6.0.2.20160510.jar" -DgroupId="com.lightstreamer" -DartifactId="sdk.client.java.se" -Dversion="6.0.2.20160510" -Dpackaging="jar"
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn  clean install
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mvn package
      - mv ig-webapi-java-sample-console/target/IG.war IG.war
artifacts:
  files:
    - IG.war
    - .ebextensions/**/*
